version: "3.3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - .dev/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=emoney
      - POSTGRES_PASSWORD=password
  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always